### ISSUE TITLE
Spring Boot 3.2 nested jar references not supported

### ISSUE THREAD

**Issue by ahazeltonNF** [libly/resource-loader#18]
When using Spring Boot 3.2, the path to the referenced jar is of the format:
`nested:/app/appName.jar/!BOOT-INF/lib/lazysodium-java-5.1.4.jar`

The “nested:” comes from the new https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html format.  And also notice the `/!` separator for the nested jar reference.

Causes:
```
2024-03-15T20:25:01.146920010Z Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
2024-03-15T20:25:01.146931299Z     at java.base/java.io.File.<init>(File.java:420)
2024-03-15T20:25:01.146933670Z     at com.goterl.resourceloader.ResourceLoader.urlToFile(ResourceLoader.java:588)
2024-03-15T20:25:01.146937295Z     at com.goterl.resourceloader.ResourceLoader.urlToFile(ResourceLoader.java:567)
```

**Comment by gurpreet-** [comment]
Solved in the above commits

**Comment by tburtchell** [comment]
A workaround until this change is released is to unpack the lazysodium jar. This can be set up using the spring boot plugin for gradle or maven.

Here's what works for us.

Gradle:
```
bootJar {
    requiresUnpack '**/lazysodium-java-*.jar'
}
```

Maven:
```
<plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <requiresUnpack>
              <dependency>
                  <groupId>com.goterl</groupId>
                  <artifactId>lazysodium-java</artifactId>
              </dependency>
          </requiresUnpack>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>build-info</goal>
                <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```

**Comment by gurpreet-** [comment]
Fixed as part of latest release [2.1.0](https://github.com/terl/resource-loader/releases/tag/v2.1.0)
